In [1]:
import numpy as np

In [2]:
arr = np.arange(1000000)

In [3]:
pylist = list(range(1000000))

In [4]:
%time for item in range(10): [item * 3 for item in pylist] # for list

CPU times: total: 281 ms
Wall time: 590 ms


In [5]:
%time for item in range(10): arr = arr*3 # for numpy

CPU times: total: 0 ns
Wall time: 22.9 ms


In [6]:
# numpy wall time is less than list wall time
# numpy written in C

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr.shape

(1000000,)

In [9]:
arr1 = np.array([[2 , 3 , 4] , [1 , 4 , 6]])
print(arr1)

[[2 3 4]
 [1 4 6]]


In [10]:
arr1.shape 

(2, 3)

In [11]:
arr1.dtype # array datatype

dtype('int32')

In [12]:
arr1.ndim # number of dimension of an array

2

In [13]:
arr1.data

In [14]:
np.ones((2 , 3))
# np.zeros(2 , 3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones(4).dtype

dtype('float64')

In [16]:
np.empty(4).dtype

dtype('float64')

In [17]:
print(arr1)

[[2 3 4]
 [1 4 6]]


In [18]:
print(arr1 * arr1)

[[ 4  9 16]
 [ 1 16 36]]


In [19]:
print(arr1 ** arr1)

[[    4    27   256]
 [    1   256 46656]]


In [20]:
print(arr1 / 2) # divide each value from array by 2

[[1.  1.5 2. ]
 [0.5 2.  3. ]]


slicing and pointer basics

In [21]:
arr2 = np.array([10 , 20 , 30 , 40 , 50 , 60])

In [22]:
arr = arr2[4:6] # slicing

In [23]:
print(arr)

[50 60]


In [24]:
arr[0] = 100 # pointer

In [25]:
print(arr2)

[ 10  20  30  40 100  60]


In [26]:
# this occur because it use pointer
# to avoid this we .copy() func

In [27]:
arr = arr2[4:6].copy()

In [28]:
print(arr)

[100  60]


In [29]:
arr[0] = 50

In [30]:
print(arr)

[50 60]


In [31]:
print(arr2)

[ 10  20  30  40 100  60]


In [32]:
arr1

array([[2, 3, 4],
       [1, 4, 6]])

In [33]:
print(arr1[1][1])

4


axis , sorting , transpose , etc 

In [34]:
print(arr1.sum(axis = 1)) # rows sum

[ 9 11]


In [35]:
print(arr1.sum(axis = 0)) # columns sum

[ 3  7 10]


In [36]:
print(arr1)

[[2 3 4]
 [1 4 6]]


In [37]:
print(arr1.transpose())

[[2 1]
 [3 4]
 [4 6]]


In [38]:
print(np.dot(arr1 , arr1.transpose()))

[[29 38]
 [38 53]]


In [39]:
b = np.array([[3 , 2 , 1] , [6 , 5, 4]])

In [40]:
print(np.cross(arr1 , b))

[[ -5  10  -5]
 [-14  32 -19]]


In [41]:
print(b)

[[3 2 1]
 [6 5 4]]


In [42]:
print(np.sort(b , axis = 1)) # sorting

[[1 2 3]
 [4 5 6]]


In [43]:
print(np.sort(b , kind = "mergedsort")) # sort array by our own choice

[[1 2 3]
 [4 5 6]]


argmin , argmax , argsort , etc

In [44]:
a = np.array([1 , 2 , 3 , 4 , 5])

In [45]:
b = np.array([11 , 22 , 33 , 44 , 55 , 66 , 77 , 88 , 99 , 100])
print(b.shape)

(10,)


In [46]:
print(b.reshape(5 , 2))

[[ 11  22]
 [ 33  44]
 [ 55  66]
 [ 77  88]
 [ 99 100]]


In [47]:
print(np.argsort(b)) # gives index of smallest value

[0 1 2 3 4 5 6 7 8 9]


In [48]:
print(np.argmax(b))

9


In [49]:
print(np.argmin(b))

0
